name: HRMIS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          username: ${{ secrets.SSH_USERNAME_STAGING }}
          script: |
            cd /var/www/hrmis/
            git checkout -f
            git pull
            npm install
            npm run build
